routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::resource('/church', 'ChurchController');
Route::resource('/author','AuthorController');
Route::resource('/member','MemberController');
Route::resource('/publisher','PublisherController');
Route::resource('/status','StatusController');
Route::resource('/book','BookController');
Route::resource('/emprestimo','LendController');
Route::get('/devolvidos','LendController@devolvidos')->name('devolvidos');


Route::get('/auth/register', function () {
    return view('auth.register')->name('register');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<pagina tamanho="10">
    <painel titulo="Dashboard">

        <div class="row">
            <div class="col-md-3">
                <caixa qtd="{{ $books->count('id') }}" titulo="Livros" url="{{ route('book.index') }}" cor="green" icone="ion ion-ios-bookmarks"></caixa>
            </div>
            <div class="col-md-3">
                <caixa qtd="{{ $lends->count('id') }}" titulo="Emprestados" url="{{ route('emprestimo.index') }}" cor="red" icone="ion ion-briefcase"></caixa>
            </div>
            <div class="col-md-3">
                <caixa qtd="{{ $members->count('id') }}" titulo="Membros" url="{{ route('member.index') }}" cor="blue" icone="ion ion-person-stalker"></caixa>
            </div>
            <div class="col-md-3">
                <caixa qtd="{{ $authors->count('id') }}" titulo="Autores" url="{{ route('author.index') }}" cor="orange" icone="ion ion-person"></caixa>
            </div>
        </div>
    </painel>
</pagina>

@endsection