routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::resource('/church', 'ChurchController');
Route::resource('/author','AuthorController');
Route::resource('/member','MemberController');
Route::resource('/publisher','PublisherController');
Route::resource('/status','StatusController');
Route::resource('/book','BookController');
Route::resource('/emprestimo','LendController');
Route::get('/devolvidos','LendController@devolvidos')->name('devolvidos');


Route::get('/auth/register', function () {
    return view('auth.register')->name('register');
});

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Model\Author;
use App\Model\Book;
use App\Model\Publisher;
use Illuminate\Http\Request;

class BookController extends Controller
{
    private $book;

    public function __construct(Book $book, Publisher $publisher, Author $author)
    {
        $this->book = $book;
        $this->publisher = $publisher;
        $this->auhtor = $author;
    }
    public function index()
    {
        $books =  Book::sortable()->paginate(50);
        $title = 'Cadastro de Livros';

        return view('book.consBook', compact('title', 'books'));
    }

    public function create()
    {
        $title = 'Cadastro de Livros';
        $publishers = Publisher::all()->sortBy('editora');
        $authors = Author::all()->sortBy('nm_autor');

        return view('book.cadBook', compact('title','publishers','authors'));
    }

    public function store(Request $request)
    {
        $dataForm = $request->all();
        $insert = $this->book->create($dataForm);

        if ($insert)
            return redirect()->route('book.index');
        else {
            return redirect()->back();
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/book/cadBook.blade.php
@extends('layouts.app')

@section('content')


  <pagina tamanho="12">
      <painel titulo="{{ $title }}">

    @if (isset($books))
        {!! Form::model($books, ['route' => ['book.update', $books->id], 'class' => 'Form', 'method' => 'PUT']) !!}
{{--        {!! Form::hidden('updated_by',Auth::user()->id) !!}--}}
    @else
        {!! Form::open(['route' => 'book.store', 'class' => 'form']) !!}
{{--        {!! Form::hidden('created_by',Auth::user()->id) !!}--}}
    @endif
            <div class="form-group">
                {!! Form::label('título', 'Título:'); !!}
                {!! Form::textarea('titulo', null, ['class' => 'form-control', 'placeholder' => 'Título completo','size' => '30x2']); !!}
            </div>
            <div class="form-group">
                {!! Form::label('author_id','Autor:') !!}
        {{--        {!! Form::select('author_id',$authors->pluck('nm_autor','id'),null,['class'=>'js-autor-placeholder js-autor form-control']) !!}--}}
                <select id="author_id" name="author_id" class="js-autor-placeholder form-control" aria-hidden="true">
                    <option></option>
                    @foreach($authors as $author)
                        <option value="{{ $author->id }}">{{ $author->nm_autor }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                {!! Form::label('publisher_id','Editora:'); !!}
        {{--        {!! Form::select('publisher_id',$publishers->pluck('editora','id'),null,['class'=>'js-editora form-control','placeholder'=>'Selecione uma editora...']); !!}--}}
                <select id="publisher_id" name="publisher_id" class="js-editora-placeholder form-control" aria-hidden="true">
                    <option></option>
                    @foreach($publishers as $publisher)
                        <option value="{{ $publisher->id }}">{{ $publisher->editora }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                {!! Form::label('datapublicacao', 'Ano de Publicação:'); !!}
                {!! Form::number('datapublicacao', null, ['class' => 'form-control','placeholder'=>'Ano de publicação']); !!}
            </div>
            <div class="form-group">
                {!! Form::label('edicao','Edição:'); !!}
                {!! Form::text('edicao',null, ['class' => 'form-control','placeholder'=>'Número da edição']); !!}
            </div>
            <div class="form-group">
                {!! Form::label('paginas','Número de páginas:'); !!}
                {!! Form::number('paginas',null,['class'=>'form-control','placeholder'=>'Número de páginas']); !!}
            </div>
            <div class="form-group">
                {!! Form::label('resumo','Resumo:') !!}
                {!! Form::textarea('resumo',null,['class'=>'form-control','placeholder'=>'Resumo do livro']); !!}
            </div>
            <div class="form-group">
                {!! Form::label('dataaquisicao', 'Data de Aquisição:'); !!}
                {!! Form::date('dataaquisicao', null, ['class' => 'form-control']); !!}
            </div>
            <div class="form-group">
                {!! Form::label('emprestimo','Disponível para empréstimo?') !!}
                {!! Form::radio('emprestimo', '1',true);!!} Sim
                {!! Form::radio('emprestimo', '0');!!} Não
            </div>
            <div class="form-group">
                {!! Form::label('preco','Preço de compra:') !!}
                {!! Form::text('preco',null,['class'=>'form-control','placeholder'=>'Valor de compra em R$']) !!}
                {!! Form::hidden('status_id','1') !!}
            </div>
                <br>
                {!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
            {{--    {{ Form::button('<i class="glyphicon glyphicon-floppy-disk"> Salvar</i>', ['type' => 'submit', 'class' => 'btn btn-primary'] )  }}--}}
                {!! Form::close() !!}
            </div>
    </painel>
</pagina>
@endsection

@section('js')

    <script>
        $(".js-autor-placeholder").select2({
            placeholder: "Selecione o autor...",
            allowClear: true
        });
        $(".js-editora-placeholder").select2({
            placeholder: "Selecione a editora...",
            allowClear: true
        });

    </script>

@endsection

resources/views/book/consBook.blade.php
@extends('layouts.app')

@section('content')

    @if (isset($errors) && count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif
<pagina tamanho="12">
    <painel titulo="{{ $title }}">

        <a href="{{ route('book.create')}}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Cadastrar</a>
        <br><br>
        <table class="table table-striped">
            <tr>
                <th width="50px">@sortablelink('id','#')</th>
                <th>@sortablelink('titulo','Título')</th>
                <th>@sortablelink('paginas','Páginas')</th>
                <th>@sortablelink('author_id','Autor')</th>
                <th>@sortablelink('datapublicacao','Publicado em')</th>
                <th>@sortablelink('emprestimo','Disponível para empréstimo?')</th>
                <th width="100px">Ações</th>
            </tr>
            @foreach ($books as $book)
                <tr>
                    <td>{{ $book->id }}</td>
                    <td>{{ $book->titulo }}</td>
                    <td>{{ $book->paginas }}</td>
                    <td>{{ $book->author->nm_autor }}</td>
                    <td>{{ $book->datapublicacao }}</td>
                    <td>{{ $book->emprestimo }}</td>
                    <td>
                        {{--@shield('book.editar')--}}
                        <a class = "btn btn-sm btn-default" href="{{ route('book.edit',$book->id)}}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        {{--@endshield--}}
                        <button type="button" title="EXCLUIR" class="btn btn-sm btn-default" data-toggle="modal" data-target="#excluir{{ $book->id }}">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>

                        <!-- Modal EXCLUIR-->
                        <div class="modal fade" id="excluir{{$book->id}}" tabindex="-1" role="dialog" aria-labelledby="excluir">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">

                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Deseja excluir?</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div align="center">
                                            <b>{{ $book->igreja }}</b>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        {!! Form::open(['route'=> ['book.destroy',$book->id], 'method'=>'DELETE']) !!}
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                                        <button type="submit" class = "btn btn-danger"> <span class="glyphicon glyphicon-trash"></span> Excluir </button>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                    </td>
                </tr>

            @endforeach
        </table>
        {!! $books->appends(\Request::except('page'))->render() !!}
      </painel>
  </pagina>
@endsection