routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::resource('/church', 'ChurchController');
Route::resource('/author','AuthorController');
Route::resource('/member','MemberController');
Route::resource('/publisher','PublisherController');
Route::resource('/status','StatusController');
Route::resource('/book','BookController');
Route::resource('/emprestimo','LendController');
Route::get('/devolvidos','LendController@devolvidos')->name('devolvidos');


Route::get('/auth/register', function () {
    return view('auth.register')->name('register');
});

app/Http/Controllers/ChurchController.php
<?php

namespace App\Http\Controllers;

use App\Model\Church;
use Illuminate\Http\Request;

class ChurchController extends Controller
{
    private $church;

    public function __construct(Church $church)
    {
        $this->church = $church;
    }
    public function index()
    {
        $churches =  Church::sortable()->paginate(10);
        $title = 'Cadastro de Igrejas';

        return view('church.consChurch', compact('title', 'churches'));
    }

    public function create()
    {
        $title = 'Cadastro de Igrejas';

        return view('church.cadChurch', compact('title'));
    }

    public function store(Request $request)
    {
        $dataForm = $request->all();
        $insert = $this->church->create($dataForm);

        if ($insert)
            return redirect()->route('church.index');
        else {
            return redirect()->back();
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $churches = Church::find($id);
        $title = "Editar Cadastro de Igreja: $churches->igreja";

        return view('church.cadChurch', compact('title', 'churches'));
    }

    public function update(Request $request, $id)
    {
        $dataForm = $request->all();
        $churches = Church::find($id);
        $update = $churches->update($dataForm);

        if ($update)
            return redirect()->route('church.index', $id);
        else
            return redirect()->route('church.edit', $id)->with(['errors' => 'Falha ao editar']);
    }

    public function destroy($id)
    {
        $churches = Church::find($id);

        $delete = $churches->delete();

        if ($delete)
            return redirect()->route('church.index');
        else
            return redirect()->route('church.index')->with(['errors' => 'Falha ao editar']);
    }
}

resources/views/church/cadChurch.blade.php
@extends('layouts.app')

@section('content')

    <div class="text-center">
        <h3>{{ $title }}</h3>
    </div>

    {{--@shield('unidade.cadastrar')--}}

    @if (isset($churches))
        {!! Form::model($churches, ['route' => ['church.update', $churches->id], 'class' => 'Form', 'method' => 'PUT']) !!}
{{--        {!! Form::hidden('updated_by',Auth::user()->id) !!}--}}
    @else
        {!! Form::open(['route' => 'church.store', 'class' => 'form']) !!}
{{--        {!! Form::hidden('created_by',Auth::user()->id) !!}--}}
    @endif

    <div class="form-group">
        {!! Form::label('igreja', 'Igreja:'); !!}
        {!! Form::text('igreja', null, ['class' => 'form-control', 'placeholder' => 'Igreja']) !!}<br>
        {!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
    {{--    {{ Form::button('<i class="glyphicon glyphicon-floppy-disk"> Salvar</i>', ['type' => 'submit', 'class' => 'btn btn-primary'] )  }}--}}
        {!! Form::close() !!}
    {{--@endshield--}}
    </div>

@endsection

resources/views/church/consChurch.blade.php
@extends('layouts.app')

@section('content')

    <div align="center">
        <h3> {{ $title }} </h3>
    </div>


    @if (isset($errors) && count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif

    {{--@shield('church.cadastrar')--}}
    <a href="{{ route('church.create')}}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Cadastrar</a>
    {{--@endshield--}}
    <br><br>
    <table class="table table-striped">
        <tr>
            <th width="50px">@sortablelink('id','#')</th>
            <th>@sortablelink('igreja','Igreja')</th>
            <th width="100px">Ações</th>
        </tr>
        @foreach ($churches as $church)
            <tr>
                <td>{{ $church->id }}</td>
                <td>{{ $church->igreja }}</td>
                <td>
                    {{--@shield('church.editar')--}}
                    <a class = "btn btn-sm btn-default" href="{{ route('church.edit',$church->id)}}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    {{--@endshield--}}
                    <button type="button" title="EXCLUIR" class="btn btn-sm btn-default" data-toggle="modal" data-target="#excluir{{ $church->id }}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>

                    <!-- Modal EXCLUIR-->
                    <div class="modal fade" id="excluir{{$church->id}}" tabindex="-1" role="dialog" aria-labelledby="excluir">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">

                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Deseja excluir?</h4>
                                </div>
                                <div class="modal-body">
                                    <div align="center">
                                        <b>{{ $church->igreja }}</b>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    {!! Form::open(['route'=> ['church.destroy',$church->id], 'method'=>'DELETE']) !!}
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                                    <button type="submit" class = "btn btn-danger"> <span class="glyphicon glyphicon-trash"></span> Excluir </button>
                                    {!! Form::close() !!}
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </td>
            </tr>

        @endforeach
    </table>
    {!! $churches->appends(\Request::except('page'))->render() !!}

@endsection