routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::resource('/church', 'ChurchController');
Route::resource('/author','AuthorController');
Route::resource('/member','MemberController');
Route::resource('/publisher','PublisherController');
Route::resource('/status','StatusController');
Route::resource('/book','BookController');
Route::resource('/emprestimo','LendController');
Route::get('/devolvidos','LendController@devolvidos')->name('devolvidos');


Route::get('/auth/register', function () {
    return view('auth.register')->name('register');
});

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Model\Author;
use App\Model\Status;
use Illuminate\Http\Request;
use App\Http\Requests\AuthorFormRequest;

class AuthorController extends Controller
{
    private $author;

    public function __construct(Author $author)
    {
        $this->author = $author;
    }

    public function index()
    {
        $authors =  Author::sortable()->paginate(10);
        $title = 'Cadastro de Autores';

        return view('author.consAuthor', compact('title', 'authors'));
    }

    public function create()
    {
        $title = 'Cadastro de Autores';
        $statuses = Status::all();

        return view('author.cadAuthor', compact('title','statuses'));
    }

    public function store(AuthorFormRequest $request)
    {
        $dataForm = $request->all();
        $insert = $this->author->create($dataForm);

        if ($insert)
            return redirect()->route('author.index');
        else {
            return redirect()->back();
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $authors = Author::find($id);
        $title = "Editar Cadastro de Autor: $authors->nm_autor";

        return view('author.cadAuthor', compact('title', 'authors'));
    }

    public function update(Request $request, $id)
    {
        $dataForm = $request->all();
        $authors = Author::find($id);
        $update = $authors->update($dataForm);

        if ($update)
            return redirect()->route('author.index', $id);
        else
            return redirect()->route('author.edit', $id)->with(['errors' => 'Falha ao editar']);
    }

    public function destroy($id)
    {
        $authors = Author::find($id);

        $delete = $authors->delete();

        if ($delete)
            return redirect()->route('author.index');
        else
            return redirect()->route('author.index')->with(['errors' => 'Falha ao editar']);
    }
}

resources/views/author/cadAuthor.blade.php
@extends('layouts.app')

@section('content')

  @if (isset($errors) && count($errors) > 0)
    <div class="alert alert-danger">
      @foreach ($errors->all() as $error)
        <p>{{ $error }}</p>
      @endforeach
    </div>
  @endif

<pagina tamanho="12">
    <painel titulo="{{ $title }}">
        @if (isset($authors))
            {!! Form::model($authors, ['route' => ['author.update', $authors->id], 'class' => 'Form', 'method' => 'PUT']) !!}
    {{--        {!! Form::hidden('updated_by',Auth::user()->id) !!}--}}
        @else
            {!! Form::open(['route' => 'author.store', 'class' => 'form']) !!}
    {{--        {!! Form::hidden('created_by',Auth::user()->id) !!}--}}
        @endif

        <div class="form-group">
            {!! Form::label('nm_autor', 'Igreja:'); !!}
            {!! Form::text('nm_autor', null, ['class' => 'form-control', 'placeholder' => 'Autor']) !!}<br>
            {!! Form::label('status_id', 'Status:'); !!}
            @if(isset($authors))
                {!! Form::select('status_id',$authors->status->pluck('descricao','id'), null, ['class' => 'form-control']) !!}<br>
            @else
                {!! Form::select('status_id',$statuses->pluck('descricao','id'), null, ['class' => 'form-control']) !!}<br>
            @endif

            {!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
        {{--    {{ Form::button('<i class="glyphicon glyphicon-floppy-disk"> Salvar</i>', ['type' => 'submit', 'class' => 'btn btn-primary'] )  }}--}}
            {!! Form::close() !!}
        </div>
    </painel>
</pagina>
@endsection

resources/views/author/consAuthor.blade.php
@extends('layouts.app')

@section('content')

  {{--  
  <div align="center">
        <h3> {{ $title }} </h3>
    </div>
    --}}

    @if (isset($errors) && count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif
<pagina tamanho="12">
    <painel titulo="{{ $title }}">
        <a href="{{ route('author.create')}}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Cadastrar</a>
        <br><br>
        <table class="table table-striped">
            <tr>
                <th width="50px">@sortablelink('id','#')</th>
                <th>@sortablelink('nm_autor','Autor')</th>
                <th>@sortablelink('status_id','Status')</th>
                <th width="100px">Ações</th>
            </tr>
            @foreach ($authors as $author)
                <tr>
                    <td>{{ $author->id }}</td>
                    <td>{{ $author->nm_autor }}</td>
                    <td>{{ $author->status->descricao }}</td>
                    <td>
                        {{--@shield('author.editar')--}}
                        <a class = "btn btn-sm btn-default" href="{{ route('author.edit',$author->id)}}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        {{--@endshield--}}
                        <button type="button" title="EXCLUIR" class="btn btn-sm btn-default" data-toggle="modal" data-target="#excluir{{ $author->id }}">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>

                        <!-- Modal EXCLUIR-->
                        <div class="modal fade" id="excluir{{$author->id}}" tabindex="-1" role="dialog" aria-labelledby="excluir">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">

                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Deseja excluir?</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div align="center">
                                            <b>{{ $author->nm_autor }}</b>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        {!! Form::open(['route'=> ['author.destroy',$author->id], 'method'=>'DELETE']) !!}
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                                        <button type="submit" class = "btn btn-danger"> <span class="glyphicon glyphicon-trash"></span> Excluir </button>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                    </td>
                </tr>

            @endforeach
        </table>
    </painel>
</pagina>
   
    {!! $authors->appends(\Request::except('page'))->render() !!}

@endsection